### ISSUE TITLE
Error listing zones

### ISSUE THREAD

**Issue by mrlesmithjr** [jpmens/ansible-m-pdns_zone#2]
I just pulled down this code and when attempting to list zones I am getting the following error. Thoughts? I have attempted to run this several different ways including your default list zones playbook but they all result in the same error. thanks.

failed: [ns1] => {"failed": true, "parsed": false}
BECOME-SUCCESS-uhwpoaxqthdfkvhwabbsdrzehuqysqtz
  File "/home/remote/.ansible/tmp/ansible-tmp-1431560484.5-231393847000146/pdns_zone", line 190
    module.fail_json(msg="failed to check zone %s at %s: %s" % (zone, url info['msg']))

**Comment by jpmens** [comment]
You're not showing me the actual output fromt he play ...
Line 190 is raised when the HTTP result from the API is not 200 (i.e. not OK); I would think either the URL you've configured is incorrect or the zone you're querying doesn't exist.

I need to see more of your play and its output.

**Comment by mrlesmithjr** [comment]
Here is the actual play. I can use the api w/out issue outside of this module so I know the api works.

thanks!
- hosts:
  - ns1
    vars:
    gather_facts: False
    tasks:
  - name: List existing zones
    action: pdns_zone action=list zone=*.local
    register: zl
  - name: Create report
    local_action: template src=a-zlist.j2 dest=/tmp/rep.out

And here is the actual output.

PLAY [ns1] *******************************************************************\* 

TASK: [List existing zones] **************************************************\* 
failed: [ns1] => {"failed": true, "parsed": false}
BECOME-SUCCESS-cmmeywpczkxljmrvptgoznnugkvgokwa
  File "/home/remote/.ansible/tmp/ansible-tmp-1431601182.92-130228390546549/pdns_zone", line 190
    module.fail_json(msg="failed to check zone %s at %s: %s" % (zone, url info['msg']))
                                                                             ^
SyntaxError: invalid syntax
OpenSSH_6.6.1, OpenSSL 1.0.1f 6 Jan 2014
debug1: Reading configuration data /etc/ssh/ssh_config
debug1: /etc/ssh/ssh_config line 19: Applying options for *
debug1: auto-mux: Trying existing master
debug1: mux_client_request_session: master session id: 2
Shared connection to ns1 closed.

FATAL: all hosts have already failed -- aborting

PLAY RECAP *******************************************************************\* 
           to retry, use: --limit @/home/administrator/a-zlist.retry

ns1                        : ok=0    changed=0    unreachable=0    failed=1

**Comment by mrlesmithjr** [comment]
## I have also attempted this playbook.
- hosts: localhost
  connection: local
  gather_facts: false
  vars_files:
  - pdns_vars.yml
    tasks:
  - name: listing zones
    action: pdns_zone 
            zone={{ item }}
            action=list
            api_key={{ pdns_api_key }}
            api_host={{ pdns_api_host }}
            api_port={{ pdns_api_port }}
    with_items: pdns_zones

## Here are the vars file.

pdns_api_key: 'changeme'
pdns_api_port: '8081'
pdns_api_host: 'ipam.everythingshouldbevirtual.local'
pdns_api_url: 'http://{{ pdns_api_host }}'
pdns_zones_url: '/servers/localhost/'
pdns_config_url: '/servers/localhost/'
pdns_create_zone_url: '/servers/localhost/zones/'
pdns_nameservers: '"ns1.everythingshouldbevirtual.local", "ns2.everythingshouldbevirtual.local"'
pdns_zone: 'everythingshouldbevirtual.local'

**Comment by jpmens** [comment]
My apologies: there really was an error in the code which is now fixed.

**Comment by mrlesmithjr** [comment]
Works perfect now. Thanks a bunch. Will be doing some extensive testing
with this module. Great job.

**Comment by mrlesmithjr** [comment]
Will you be adding action=native so that Native zones can be created as
well?

**Comment by jpmens** [comment]
Please test

**Comment by mrlesmithjr** [comment]
Will do. Much appreciated.

Twitter @mrlesmithjr http://twitter.com/mrlesmithjr
Blog EverythingShouldBeVirtual.com
Interested in blog sponsorship? Go to http://bit.ly/10Aj7Sq

**Comment by mrlesmithjr** [comment]
Works perfect..Thanks a ton.

**Comment by mrlesmithjr** [comment]
Any thoughts on adding functionality to create rrset records as well? Time
for me to now learn python. :)

Twitter @mrlesmithjr http://twitter.com/mrlesmithjr
Blog EverythingShouldBeVirtual.com
Interested in blog sponsorship? Go to http://bit.ly/10Aj7Sq
